#!/usr/bin/bash
set -e
shopt -s nullglob

Red='\033[0;31m'
Green='\033[0;32m'
Cyan='\033[0;36m'
Yellow='\033[0;33m'
Reset='\033[0m'
Bold='\033[1m'
Gray='\033[0;90m'

warn()
{
    echo -e "${Yellow}${Bold}warning: ${Reset}$1"
}

die()
{
    echo -e "${Red}${Bold}error: ${Reset}$1"
    exit 1
}

usage()
{
    [[ ! -z $1 ]] && echo -e "${Red}${Bold}error: ${Reset}$1\n"
    echo -e "\
${Green}${Bold}Usage: ${Cyan}${Bold}$0 ${Cyan}[--nocontainer] <REPOSITORY>

${Green}${Bold}Options:
  ${Cyan}${Bold}--nocontainer  ${Reset}Build the image without using a container

${Green}${Bold}Parameters:
  ${Cyan}${Bold}REPOSITORY  ${Reset}Path to directory with meowzips on host system"
    exit 2
}

bNoContainer=0

eval set -- "$(getopt --name "$0" --options '' --long nocontainer -- "$@")"
while : ; do
    case "$1" in
        --nocontainer) bNoContainer=1 ; shift ;;
        --           ) shift          ; break ;;
        *            )                  usage ;;
    esac
done

dRepo="$1"

[[   -z $dRepo ]] && usage "Missing positional argument REPOSITORY" 
[[ ! -d $dRepo ]] && die "$dRepo does not exist"

if [[ $bNoContainer -eq 0 ]]; then
    exec docker run --privileged --rm -it               \
                    -v "$dRepo":/root/repo               \
                    -v "$PWD":/root/meow                  \
                    docker.io/rustlang/rust:nightly-trixie \
                    /root/meow/create-image --nocontainer /root/repo
fi

apt update
apt install -y arch-install-scripts

cd ~/meow
make
make install

meow-pkg --root /mnt install "$dRepo/meow-config-1.0.0-1.mz" --breakdeps
for fPkg in "$dRepo"/*.mz; do
    [[ $(basename "$fPkg") == meow-config-1.0.0-1.mz ]] && continue
    echo -e "${Gray}Installing package ${Bold}$(basename "$fPkg")${Reset}"
    meow-pkg --root /mnt install "$fPkg" --breakdeps
done

make DESTDIR=/mnt PREFIX=/usr install

cat | arch-chroot /mnt /usr/bin/bash << "EOF"
touch /var/log/{btmp,lastlog,faillog,wtmp}
chgrp -v utmp /var/log/lastlog
chmod -v 664  /var/log/lastlog
chmod -v 600  /var/log/btmp
pwconv
grpconv
printf 'admin\n' | passwd -s root
udev-hwdb update
echo meow > /etc/hostname
cat > /etc/fstab << "EOF2"
# Begin /etc/fstab

# file system  mount-point    type     options             dump  fsck
#                                                                order

/dev/<xxx>     /              <fff>    defaults            1     1
/dev/<yyy>     swap           swap     pri=1               0     0
proc           /proc          proc     nosuid,noexec,nodev 0     0
sysfs          /sys           sysfs    nosuid,noexec,nodev 0     0
devpts         /dev/pts       devpts   gid=5,mode=620      0     0
tmpfs          /run           tmpfs    defaults            0     0
devtmpfs       /dev           devtmpfs mode=0755,nosuid    0     0
tmpfs          /dev/shm       tmpfs    nosuid,nodev        0     0
cgroup2        /sys/fs/cgroup cgroup2  nosuid,noexec,nodev 0     0

# End /etc/fstab
EOF2
make-ca -g
cat > /etc/hosts << "EOF2"
127.0.0.1  localhost meow
::1        localhost
EOF2
ln -svf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
exit
EOF

rm -f rootfs.tar.xz
echo -e "${Gray}Creating rootfs tarball...${Reset}"
tar -cJf rootfs.tar.xz -C /mnt .
echo -e "\n${Green}${Bold}Done!${Reset}"
