#!/usr/bin/bash
set -e
shopt -s nullglob

Red='\033[0;31m'
Green='\033[0;32m'
Cyan='\033[0;36m'
Yellow='\033[0;33m'
Reset='\033[0m'
Bold='\033[1m'
Gray='\033[0;90m'

warn()
{
    echo -e "${Yellow}${Bold}warning: ${Reset}$1"
}

die()
{
    echo -e "${Red}${Bold}error: ${Reset}$1"
    exit 1
}

usage()
{
    [[ ! -z $1 ]] && echo -e "${Red}${Bold}error: ${Reset}$1\n"
    echo -e "\
${Green}${Bold}Usage: ${Cyan}${Bold}$0 ${Cyan}[-i] <RECIPE>

${Green}${Bold}Options:
  ${Cyan}${Bold}-i  ${Reset}Drop into an interactive shell instead of running build()

${Green}${Bold}Parameters:
  ${Cyan}${Bold}RECIPE  ${Reset}Path to recipe directory"
    exit 2
}

[[ ! -f ~/.config/meow-craft ]] && die "~/.config/meow-craft does not exist"
source ~/.config/meow-craft
[[ -z $packager ]] && die "Missing packager= in config"
sources_directory="${sources_directory:-$HOME/.cache/meow-craft/sources}"
builds_directory="${builds_directory:-$HOME/.cache/meow-craft/builds}"
mkdir -p "$sources_directory" "$builds_directory"

bInteractive=0

eval set -- "$(getopt --name "$0" --options i -- "$@")"
while : ; do
    case "$1" in
        -i ) bInteractive=1 ; shift ;;
        -- ) shift          ; break ;;
        *  )                  usage ;;
    esac
done

dRecipe="$1"

[[   -z $dRecipe        ]] && usage "Missing path to recipe directory"
[[ ! -d $dRecipe        ]] && die "Path to recipe directory does not exist"
[[ ! -f $dRecipe/recipe ]] && die "Recipe \`$dRecipe/recipe\` does not exist"

source $dRecipe/recipe
[[ -z $name          ]] && die "Missing name= in recipe"
[[ -z $version       ]] && die "Missing version= in recipe"
[[ -z $release       ]] && die "Missing release= in recipe"
[[ -z $source        ]] && die "Missing source= in recipe"
[[  ! $release -gt 0 ]] && die "release= in recipe is invalid"
[[ -z $license       ]] && warn "Recipe does not have license= variable specified"

if [[ ! -f ~/.minisign/minisign.key ]]; then
    die "Minisign key not found, generate it with \`minisign -G\` with an empty password"
fi

echo -e "${Green}${Bold}Downloading... ${Reset}$source"
wget -nc -q --show-progress -P "$sources_directory" "$source"

dSource="$sources_directory/$name"
rm -rf "$dSource"
mkdir "$dSource"
tar -C "$dSource" -xf "$sources_directory/$(basename $source)"
tmp=("$dSource"/*); [[ -d ${tmp[@]} ]] && dSource="$dSource/$(basename "$tmp")"

for fPatch in "$dRecipe"/*.patch; do
    patch -Np1 -i "$PWD/$fPatch" -d "$dSource"
done


export DESTDIR="$builds_directory/$name-$version-$release"
rm -rf "$DESTDIR"
mkdir "$DESTDIR"

export recipe="$(realpath "$dRecipe")"

if [[ $bInteractive -eq 1 ]]; then
    echo -e "${Green}${Bold}Dropping into interactive shell"
    echo -e "${Gray}(type ${Bold}\`exit\`${Gray} to continue packaging or ${Bold}\`exit 1\`${Gray} to abort)${Reset}"
    bash -c "set -e; source '$dRecipe/recipe'; cd '$dSource'; bash -i" || exit 0
else
    bash -c "set -e; source '$dRecipe/recipe'; cd '$dSource'; build" || die "build() failed"
fi

for fHook in {pre,post}-{install,remove}; do
    cp "$dRecipe/$fHook" "$DESTDIR/" 2> /dev/null || true
done

for fLicense in "$dSource"/copying*   \
                "$dSource"/license*   \
                "$dSource"/Copying*   \
                "$dSource"/License*   \
                "$dSource"/COPYING*   \
                "$dSource"/LICENSE*   \
                "$dSource"/*/copying* \
                "$dSource"/*/license* \
                "$dSource"/*/Copying* \
                "$dSource"/*/License* \
                "$dSource"/*/COPYING* \
                "$dSource"/*/LICENSE* ; do
    install -Dm644 "$fLicense" -t "$DESTDIR/usr/share/licenses/$name"
done

[[ ! -d $DESTDIR/usr/share/licenses/$name ]] && warn "No licenses were installed"

rm -rf "$DESTDIR"/usr/share/{info,doc}
rmdir -p --ignore-fail-on-non-empty "$DESTDIR/usr/share" 2> /dev/null || true

echo -e "${Green}${Bold}Stripping binaries and libraries...${Reset}"
for i in $(find "$DESTDIR"/usr/lib -type f -name \*.so* ! -name \*dbg) \
         $(find "$DESTDIR"/usr/lib -type f -name \*.a)                 \
         $(find "$DESTDIR"/usr/{bin,sbin,libexec} -type f); do
    strip --strip-debug "$i" 2> /dev/null || true
done

echo -e "${Green}${Bold}Creating meowzip...${Reset}"
rm -f "$DESTDIR.mz"
cd "$DESTDIR"
meow-zip create "$DESTDIR.mz"  \
         --name     "$name"    \
         --version  "$version" \
         --release  "$release" \
         --depends  "$depends" \
         --license  "$license" \
         --packager "$packager"
meow-zip list "$DESTDIR.mz"
echo -e "${Green}${Bold}Built package at ${Reset}\`$DESTDIR.mz\`"
